### ISSUE TITLE
Dry Run is Successful but Deploy isn't

### ISSUE THREAD

**Issue by sampoder** [hackclub/dns#284]
Ok, so we had #278. This hasn't worked for a while. You can see the commits. The OctoDNS says the dry run's good but then deploy never is. Matthew & I are very much stuck.

Currently we have added this record:

```
summer:
- ttl: 1
  type: A
  value: 104.198.14.52
- ttl: 3600
  type: TXT
  value: v=spf1 include:_spf.google.com ~all
- ttl: 3600
  type: MX
  values:
  - exchange: aspmx.l.google.com.
    preference: 1
  - exchange: alt1.aspmx.l.google.com.
    preference: 5
  - exchange: alt2.aspmx.l.google.com.
    preference: 5
  - exchange: alt3.aspmx.l.google.com.
    preference: 10
  - exchange: alt4.aspmx.l.google.com.
    preference: 10
```

Which is the same thing as this pre-existing record:

```

alpharetta:
- ttl: 1
  type: A
  value: 104.248.78.24
- ttl: 3600
  type: TXT
  value: v=spf1 include:_spf.google.com ~all
- ttl: 3600
  type: MX
  values:
  - exchange: aspmx.l.google.com.
    preference: 1
  - exchange: alt1.aspmx.l.google.com.
    preference: 5
  - exchange: alt2.aspmx.l.google.com.
    preference: 5
  - exchange: alt3.aspmx.l.google.com.
    preference: 10
  - exchange: alt4.aspmx.l.google.com.
    preference: 10

```

I'm not sure why it's failing to deploy but we've tried a lot of things. See #279 #280 #281 #282 & #283 lol
