### ISSUE TITLE
Issue changing tist.hackclub.com CNAME record to A record

### ISSUE THREAD

**Issue by Farzanfa** [hackclub/dns#385]
Initially the subdomain tist.hackclub.com got deployed and was working fine. with cname : HackClub-TIST.github.io

Later we got the G suite for tist.hackclub.com , in order to configure g suite, the mx record was added and the dry run was successful and merged by @lachlanjc but deploy isn’t successful

error: “requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:https://api.dnsimple.com/v2/***/zones/hackclub.com/records”

we found out that when we add a new records are getting deployed to DNS but when we delete/change a record, the deploy fails.

@hackclub/core We are stuck now and could really use your help.

I am attaching the required stuff we need below.
```
tist:
- ttl: 1
  type: A
  value: 104.198.14.52
- ttl: 3600
  type: TXT
  value: 
  - v=spf1 include:_spf.google.com ~all
  - google-site-verification=lwxLcm8yYFFYkHdZxXUoO00wJ48SCNPRn6ZdAhKoHjA
- ttl: 3600
  type: MX
  values:
  - exchange: aspmx.l.google.com.
    preference: 1
  - exchange: alt1.aspmx.l.google.com.
    preference: 5
  - exchange: alt2.aspmx.l.google.com.
    preference: 5
  - exchange: alt3.aspmx.l.google.com.
    preference: 10
  - exchange: alt4.aspmx.l.google.com.
    preference: 10
```
